/**
 * FIX-014: Anthropic prompt caching helpers.
 *
 * Anthropic accepts `cache_control: { type: 'ephemeral' }` on individual
 * content blocks, tools, and system blocks. Cache hits are prefix-based — a
 * breakpoint caches everything up to (and including) that block. A request
 * may have at most 4 cache breakpoints.
 *
 * Kova places 3 breakpoints per call:
 *   1. system prompt (last text block)
 *   2. tools array (last tool)
 *   3. history (last content block of the last message)
 *
 * The fourth slot is intentionally left free for callers that need to add an
 * additional document or context block at runtime.
 *
 * These helpers are pure: they return new arrays/objects and never mutate the
 * input.
 */

import type Anthropic from '@anthropic-ai/sdk'

const EPHEMERAL: Anthropic.Messages.CacheControlEphemeral = { type: 'ephemeral' }

/**
 * Convert a system prompt string into a cached `TextBlockParam[]`.
 * Returns `undefined` when the system prompt is empty so the caller can omit
 * the `system` parameter entirely (rather than sending an empty block).
 */
export function withCachedSystem(system: string | undefined): Anthropic.Messages.TextBlockParam[] | undefined {
  if (!system || !system.trim()) return undefined
  return [{ type: 'text', text: system, cache_control: EPHEMERAL }]
}

/**
 * Mark the LAST tool with `cache_control`. Anthropic caches the entire tools
 * array as a single unit when any tool carries a cache breakpoint, so a
 * single marker on the last tool is sufficient.
 */
export function withCachedTools(tools: readonly Anthropic.Tool[]): Anthropic.Tool[] {
  if (tools.length === 0) return []
  const result = tools.map(t => ({ ...t }))
  result[result.length - 1] = { ...result[result.length - 1], cache_control: EPHEMERAL }
  return result
}

/**
 * Mark the last content block of the last message with `cache_control`. This
 * is the "moving" breakpoint: in a multi-turn agent loop it advances every
 * iteration, growing the cached prefix that subsequent calls can read.
 *
 * String content is normalised into a single text block before marking. An
 * empty array is left empty (no breakpoint, no crash).
 */
export function withHistoryCacheBreakpoint(
  history: readonly Anthropic.Messages.MessageParam[],
): Anthropic.Messages.MessageParam[] {
  if (history.length === 0) return []
  const result = history.map(m => ({ ...m }))
  const lastIndex = result.length - 1
  const last = result[lastIndex]

  if (typeof last.content === 'string') {
    result[lastIndex] = {
      ...last,
      content: [{ type: 'text', text: last.content, cache_control: EPHEMERAL }],
    }
    return result
  }

  // Array content — find the last block and add cache_control to it.
  // Skip when there are no blocks to mark.
  if (last.content.length === 0) return result

  const blocks: Anthropic.Messages.ContentBlockParam[] = last.content.map(
    b => ({ ...b }) as Anthropic.Messages.ContentBlockParam,
  )
  blocks[blocks.length - 1] = addCacheControl(blocks[blocks.length - 1])
  result[lastIndex] = { ...last, content: blocks }
  return result
}

/**
 * Add `cache_control` to a single content block. All param shapes that the
 * Anthropic SDK accepts in `MessageParam.content` carry an optional
 * `cache_control` field, so the cast is sound.
 */
function addCacheControl<T extends Anthropic.Messages.ContentBlockParam>(block: T): T {
  return { ...block, cache_control: EPHEMERAL } as T
}

export interface ParsedCacheUsage {
  /** Tokens that were written into the cache during this request (1.25× cost). */
  cacheCreationInputTokens: number
  /** Tokens read from cache (0.10× cost — the win). */
  cacheReadInputTokens: number
  /** Non-cached input tokens consumed (full price). */
  inputTokens: number
  /** Output tokens generated by the model. */
  outputTokens: number
}

/**
 * Normalise Anthropic's `Usage` payload to a strict numeric shape. Older SDK
 * responses (and providers that surface a partial usage) may omit the cache
 * counters or set them to `null` — both cases coerce to 0.
 */
export function parseCacheUsage(usage: Anthropic.Messages.Usage): ParsedCacheUsage {
  return {
    cacheCreationInputTokens: usage.cache_creation_input_tokens ?? 0,
    cacheReadInputTokens: usage.cache_read_input_tokens ?? 0,
    inputTokens: usage.input_tokens ?? 0,
    outputTokens: usage.output_tokens ?? 0,
  }
}
