import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest'
import { existsSync, mkdtempSync, readFileSync, rmSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { EngineManager } from '../src/main/engine-manager'
import type { ProviderResolution, StartTaskParams } from '../src/main/engine-manager'
import type { AgentLoopOptions, AgentProvider, LLMResponse } from '@kova/agent'
import type { AgentMessage, ExecutionEvent, ExecutionState, FileChange, TaskDefinition } from '@kova/shared'

function landingFiles(): Array<{ path: string; content: string }> {
  return [
    {
      path: 'index.html',
      content: [
        '<!doctype html>',
        '<html lang="pt-BR">',
        '<head>',
        '  <meta charset="utf-8" />',
        '  <meta name="viewport" content="width=device-width, initial-scale=1" />',
        '  <title>Kova Dogfood Landing</title>',
        '  <link rel="stylesheet" href="./styles.css" />',
        '</head>',
        '<body>',
        '  <header class="site-header">',
        '    <strong>Kova Studio</strong>',
        '    <nav><a href="#features">Recursos</a><a href="#workflow">Workflow</a><a href="#contact">Contato</a></nav>',
        '  </header>',
        '  <main class="hero">',
        '    <p class="eyebrow">Dogfood real</p>',
        '    <h1>Kova gerou esta landing page</h1>',
        '    <p>Fluxo e2e: EngineManager, ExecutionEngine, Agent e ToolExecutor.</p>',
        '    <a class="cta" href="#contact">Comecar agora</a>',
        '  </main>',
        '  <section id="features" class="features">',
        '    <article><h2>Chat global</h2><p>Converse antes de anexar uma pasta e preserve o contexto.</p></article>',
        '    <article><h2>Modo code</h2><p>Ao anexar projeto, o Kova pode criar arquivos reais com revisao.</p></article>',
        '    <article><h2>Validacao</h2><p>Eventos, prova e status ficam auditaveis durante a execucao.</p></article>',
        '  </section>',
        '  <section id="workflow" class="workflow">',
        '    <h2>Workflow enterprise</h2>',
        '    <p>Planeje, gere, valide, revise e aplique mudancas sem esconder falhas.</p>',
        '    <ul><li>Contexto visivel</li><li>Repair explicito</li><li>Diff antes do apply</li></ul>',
        '  </section>',
        '  <section id="contact" class="contact">',
        '    <h2>Pronto para construir</h2>',
        '    <p>Este artefato prova que o fluxo e2e materializou uma interface completa.</p>',
        '    <a class="cta secondary" href="mailto:hello@kova.local">Falar com Kova</a>',
        '  </section>',
        '  <footer>Generated by Kova dogfood e2e</footer>',
        '  <script src="./script.js"></script>',
        '</body>',
        '</html>',
        '',
      ].join('\n'),
    },
    {
      path: 'styles.css',
      content: [
        ':root { color-scheme: dark; font-family: Inter, system-ui, sans-serif; --bg:#081014; --panel:#102027; --ink:#eef7fb; --muted:#9ab0b8; --accent:#9ee8ff; }',
        '* { box-sizing: border-box; }',
        'body { margin: 0; min-height: 100vh; background: radial-gradient(circle at top, #17323c, var(--bg) 48%); color: var(--ink); }',
        '.site-header { position: sticky; top: 0; display: flex; justify-content: space-between; align-items: center; padding: 18px clamp(20px, 5vw, 72px); background: rgba(8,16,20,.82); backdrop-filter: blur(18px); border-bottom: 1px solid rgba(158,232,255,.18); }',
        'nav { display: flex; gap: 18px; flex-wrap: wrap; }',
        '.hero { min-height: 72vh; display: grid; place-content: center; gap: 18px; padding: 72px clamp(24px, 7vw, 120px); }',
        '.eyebrow { color: var(--accent); text-transform: uppercase; letter-spacing: .08em; font-weight: 800; }',
        'h1 { max-width: 820px; font-size: clamp(42px, 8vw, 104px); line-height: .92; margin: 0; }',
        'h2 { margin: 0 0 10px; font-size: clamp(24px, 4vw, 44px); }',
        'p { max-width: 680px; color: var(--muted); font-size: clamp(16px, 2vw, 20px); line-height: 1.65; }',
        'a { color: inherit; text-decoration: none; }',
        '.cta { color: #081014; background: var(--accent); padding: 13px 18px; border-radius: 8px; font-weight: 800; width: max-content; box-shadow: 0 18px 50px rgba(158,232,255,.18); }',
        '.cta.secondary { background: transparent; color: var(--accent); border: 1px solid rgba(158,232,255,.36); }',
        '.features { display: grid; grid-template-columns: repeat(3, minmax(0, 1fr)); gap: 16px; padding: 48px clamp(24px, 7vw, 120px); }',
        'article, .workflow, .contact { background: rgba(16,32,39,.72); border: 1px solid rgba(158,232,255,.16); border-radius: 8px; padding: 24px; }',
        '.workflow, .contact { margin: 18px clamp(24px, 7vw, 120px); }',
        'ul { color: var(--muted); line-height: 1.9; }',
        'footer { padding: 32px clamp(24px, 7vw, 120px); color: var(--muted); }',
        '@media (max-width: 760px) { .site-header { align-items: flex-start; flex-direction: column; gap: 12px; } .features { grid-template-columns: 1fr; } .hero { min-height: 58vh; } }',
        '',
      ].join('\n'),
    },
    {
      path: 'script.js',
      content: [
        'document.documentElement.dataset.generatedBy = "kova-dogfood";',
        '',
      ].join('\n'),
    },
  ]
}

function toChanges(files: Array<{ path: string; content: string }>): FileChange[] {
  return files.map(file => ({
    path: file.path,
    type: 'create',
    diff: file.content.split('\n').map(line => `+${line}`).join('\n'),
  }))
}

function makeDogfoodProvider(): AgentProvider {
  const files = landingFiles()
  return {
    capabilities: () => ({ supportsToolCalls: true, contextTokenLimit: 32_000 }),
    generate: vi.fn().mockResolvedValue({
      thought: [
        '<task>',
        '  <title>Generate a static landing page dogfood</title>',
        '  <type>feature</type>',
        '  <impact>medium</impact>',
        '  <files>',
        '    <file>index.html</file>',
        '    <file>styles.css</file>',
        '    <file>script.js</file>',
        '  </files>',
        '</task>',
      ].join('\n'),
      changes: [],
      tokensUsed: 12,
    } as LLMResponse),
    runAgentLoop: vi.fn().mockImplementation(async (_messages: AgentMessage[], options: AgentLoopOptions) => {
      options.onToken?.('Gerando landing page dogfood...\n')
      for (const file of files) {
        const input = { path: file.path, content: file.content }
        options.onToolCall?.('write_file', input)
        const result = await options.executor.execute('write_file', input)
        options.onToolResult?.('write_file', result)
      }
      return {
        thought: 'Landing page gerada com index.html, styles.css e script.js.',
        changes: toChanges(files),
        tokensUsed: 64,
      } as LLMResponse
    }),
  }
}

function makeParams(projectRoot: string): StartTaskParams {
  return {
    objective: 'Crie uma landing page estatica pequena para validar dogfood e2e.',
    projectRoot,
    provider: 'dogfood',
    model: 'deterministic-dogfood',
    mode: 'patch',
    maxIterations: 2,
    autoApply: true,
    permissionMode: 'auto-review',
  }
}

describe('Kova dogfood generation e2e', () => {
  let projectRoot: string

  beforeEach(() => {
    projectRoot = mkdtempSync(join(tmpdir(), 'kova-dogfood-e2e-'))
  })

  afterEach(() => {
    rmSync(projectRoot, { recursive: true, force: true })
  })

  it('asks Kova to generate a landing page and observes a complete non-repairing run', async () => {
    const provider = makeDogfoodProvider()
    const resolution: ProviderResolution = {
      provider,
      resolvedProvider: 'dogfood',
      resolvedModel: 'deterministic-dogfood',
      fallback: false,
    }
    const events: ExecutionEvent[] = []
    const states: ExecutionState[] = []
    const tasks: TaskDefinition[] = []
    const chatMessages: string[] = []
    const manager = new EngineManager(async () => resolution)
    manager.setHandlers(
      state => states.push(state),
      task => tasks.push(task),
      message => chatMessages.push(message),
      vi.fn(),
      message => chatMessages.push(message),
      event => events.push(event),
    )

    await manager.sendMessage('Crie uma landing page estatica pequena para validar dogfood e2e.', [], makeParams(projectRoot))

    expect(tasks[0]?.objective).toContain('landing page')
    expect(vi.mocked(provider.runAgentLoop)).toHaveBeenCalled()
    expect(existsSync(join(projectRoot, 'index.html'))).toBe(true)
    expect(existsSync(join(projectRoot, 'styles.css'))).toBe(true)
    expect(existsSync(join(projectRoot, 'script.js'))).toBe(true)
    expect(readFileSync(join(projectRoot, 'index.html'), 'utf-8')).toContain('Kova gerou esta landing page')
    expect(events.some(event => event.type === 'tool_call' && event.toolName === 'write_file')).toBe(true)
    expect(events.some(event => event.type === 'diff_review_ready')).toBe(true)
    expect(events.some(event => event.type === 'stream_end')).toBe(true)
    expect(states.some(state => state.status === 'repairing')).toBe(false)
    expect(states.at(-1)?.status).not.toBe('failed')
    expect(chatMessages.join('\n')).not.toContain('Provider not configured')
    expect(['completed', 'paused']).toContain(manager.getState()?.status)
  })
})
